### ISSUE TITLE
Mosaico extension bootstraps civi/drupal to load an img

### ISSUE THREAD

**Issue by rocxa** [veda-consulting-company/uk.co.vedaconsulting.mosaico#55]
```
 <item>
    <path>civicrm/mosaico/img</path>
    <page_callback>CRM_Mosaico_Utils::processImg</page_callback>
    <title>Integration with Mosaico</title>
    <access_callback>1</access_callback>
    <is_public>true</is_public>
  </item>
```

Above code means that when an image is requested by a user, CiviCRM and Drupal are bootstrapped to display the image.

Suggested fix:
- Bypass CiviCRM when loading images by creating an external script to process images instead e.g. /extension/extern/processimg.php
- Create an htaccess alias that goes from civicrm/mosaico/img to the above file.
- Stop imagemagick resizing images every time they are loaded as it is highly inefficient

**Comment by rocxa** [comment]
Another part of this is that the mosaico images are not cached by default.

In Utils.php  this should be added at line 247:

 ```
               $expiry_time = 2592000;  //30days (60sec * 60min * 24hours * 30days)
                header("Pragma: cache");
                header("Cache-Control: max-age=".$expiry_time.", public");
                header('Expires: ' . gmdate('D, d M Y H:i:s', time()+$expiry_time) . ' GMT');
                header("Content-type:" . $mime_type );
                echo $image;
```

**Comment by deepak-srivastava** [comment]
@rocxa thanks for discussions on hangout and looking into these issues. Keep in touch.

**Comment by rocxa** [comment]
https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/pull/57

**Comment by jusfreeman** [comment]
Just noting that this issue is a significant problem for relatively small email-outs < 1,000.
Is not specific to Drupal, also applies to WordPress and I expect to Joomla too.

This merged PR does not appear to have solved the problem.
