### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by mfuggle** [veda-consulting-company/uk.co.vedaconsulting.mosaico#56]
I have just installed the latest version of the Mosaico extension. I am running Drupal 4.6.21. Everything installs as expected but when I try to create a Mosaico template I just get a black screen.
Is this happening to anyone else?

**Comment by rocxa** [comment]
The best place to start to work out what is wrong is look in your browsers console log.  Mosaico logs javascript errors to the console and if you are just getting a blank screen it suggest a js error has occured.

**Comment by mfuggle** [comment]
I have attached the console log from the time the extension was enabled, to
selecting email template menu item and then trying to create a Mosaico
template.

Martin Fuggle

kew: (03) 9817 1401
deans marsh: (03) 5236 3306
mobile: 0408 265 586

**Comment by rocxa** [comment]
Your attachment doesn't appear to have come through. I suspect github removes attachments to emails that are email replies to comments on github.

You can attach files by replying directly on github though.. drag and drop into the comment box window.

**Comment by mfuggle** [comment]
Here is the attachment showing the console log. I suspect the problem relates to file permissions but all other extensions I am using function without change so I am reluctant to change any permissions without understanding why. Then again the problem maybe nothing to do with permissions!
![mosaico_log](https://cloud.githubusercontent.com/assets/1777429/19708754/b1095640-9b6c-11e6-8464-de86f2084dcd.jpg)

**Comment by rocxa** [comment]
This looks like a permissions problem. Your browser is failing to read css and js files from the extensions directory.

It is affecting civi desk extension as well.

I would check the permissions other extensions files/directories have that appear to work and apply those to mosaico & cividesk.  generally speaking, the files need to be owned by (or be in the group of) the webserver (apache or httpd).

Depending on how an extension gets on to your web server (download via civi vs manual upload via ftp) files and directories will get different permissions.

**Comment by rocxa** [comment]
This looks like a permissions problem. Your browser is failing to read css
and js files from the extensions directory.

It is affecting civi desk as well.

I would check the permissions other extensions files/directories have that
appear to work and apply those to mosaico & cividesk.

Depending on how an extension gets on to your web server (download via civi
vs manual upload via ftp) files and directories will get different
permissions.

**Comment by mfuggle** [comment]
I have checked the permissions and the extension was owned by root. I have changed that to make it owned by the webserver (www-data:www-data) and the issue remains as before. I have also changed the permissions of the js directory to 777 and the log still shows that the js directory cannot be accessed.
I am very keen to use this extension but unfortunately I am at the limit of my skill set to get it working.

**Comment by rocxa** [comment]
If you click on one of the GET errors you have shown in your screen shot, do you get any more information about the error? a page with access denied? white screen? error 404 not found? etc

**Comment by mfuggle** [comment]
On the attached screen shot of the log it shows that index.js and index2.js generate a 403 error. They are both in the js directory. If I change the permissions on index.js to 777 I still get the same error.
![2016-10-27_09-02-21](https://cloud.githubusercontent.com/assets/1777429/19747115/8a178e76-9c25-11e6-940e-a4df0ff8366d.jpg)

**Comment by rocxa** [comment]
So it is clear it is an 'Access denied' problem for those js files.  If you click on knockout.js or index.js you 'may' get an even more useful error message?

Either there is a permissions problem further up the directory chain stopping the browser reading those files or there is something in a firewall/server config denying access to those files.

The apache/httpd logs should be able to shed some light on it.

**Comment by mfuggle** [comment]
I have set the permissions on the uk.co.vedaconsulting.mosaico directory and contents to 777 and still get the same result. I appreciate your help but I am not sure what else will cause a 403 error. In researching this issue it seems that all of the suggestions for solving the issue do not apply to my environment. Hmmm

**Comment by ae6** [comment]
Wondering if an .htaccess file is blocking .js files for the extension directory or an earlier directory like /sites/default/files

The black screen sounds like ImageMagick may not be installed (or correctly installed) - but since the above is referencing permissions, I would go with that.

If ImageMagick is not installed though, you can use yum (for Linux) to install ImageMagick6 ImageMagick6-devel and ImageMagick6-perl (version 6.9.6.8 from the repo of your choice).  Although, there are some major vulnerabilities with versions below 6.9.3-10 (see:  https://www.us-cert.gov/ncas/current-activity/2016/05/04/ImageMagick-Vulnerability ).  If your repo does not contain an appropriate version, the @remi repo has 6.9.6.8, and also has the pctl php extension (ex. if using php 5.6, you could install php56-php-pecl-imagick using yum).  

Just a thought if it helps - if not just disregard
