### ISSUE TITLE
Images upload and appear in template builder but not displayed in email

### ISSUE THREAD

**Issue by matt-carboncoop** [veda-consulting-company/uk.co.vedaconsulting.mosaico#71]
Congratulations on a fabulous project, it's such a leap forward for civimail.
I can upload images which resize beautifully and appear in the template builder, I can drag images into the gallery. In both cases the images end up in /public/htdocs/wp-content/plugines/files/civicrm/persist/contribute/images directory. 
When I send the email, there are no images displayed - where I've included a link and an alt-tag with the image, linked text is shown and works fine, just no image. When I logout and back in again, the images are all still there in the template however my gallery is empty...
I've tried running the runcheck=1 and it throws no errors.

Any ideas? Running the latest beta with wordpress 4.6.1 and civicrm 4.7.11

**Comment by deepak-srivastava** [comment]
Can you inspect the email and see whats the url is for missing images? Is it any different from the image url when you see the template?

**Comment by matt-carboncoop** [comment]
Hey Deepak, 
Thanks for the response. I don't even see a broken image symbol in my mail client, but going to the mail source you can see that it's pretty messed up. 

<img src="/civicrm?page=CiviCRM&amp;q=civicrm/mosaico/img&amp;src=http%3A%2F%2Fwww.yorkshirecnd.org.uk%2Fwp-content%2Fplugins%2Ffiles%2Fcivicrm%2Fpersist%2Fcontribute%2Fimages%2Fuploads%2FYCND_logo_17c13b9d26261268ac2817d4504e290c.png&amp;method=resize&amp;params=534%2Cnull" width="534" vspace="0" hspace="0" border="0">

It should be <img src="http://www.yorkshirecnd.org.uk/wp-content/plugins/files/civicrm/persist/contribute/images/uploads/YCND_logo_17c13b9d26261268ac2817d4504e290c.png"

My CiviCRM upload directory settings for images were "[civicrm.files]/persist/contribute/", I've tried setting them to the full url but I still end up with the mosaico location appended.
Any thoughts?

Many thanks,
Matt

**Comment by deepak-srivastava** [comment]
Seems like "/civicrm?page=CiviCRM&q=civicrm/mosaico/img&" type url its trying to build is - http://www.yorkshirecnd.org.uk/civicrm?page=CiviCRM&q=civicrm/mosaico/img&src=http%3A%2F%2Fwww.yorkshirecnd.org.uk%2Fwp-content%2Fplugins%2Ffiles%2Fcivicrm%2Fpersist%2Fcontribute%2Fimages%2Fuploads%2FYCND_logo_17c13b9d26261268ac2817d4504e290c.png&method=resize&params=534%2Cnull

Which looks correct except that the domain name is missing. Any ideas why that would be missing? May be something to do with base url?

Ideally the url format should be like what you said. Its currently in development and will be part of next release. Relevant ticket - https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/55.

**Comment by matt-carboncoop** [comment]
Thanks again Deepak - checked my base url in civi settings file and all seems correct. Section only specifies Drupal and Joomla though, so not sure wordpress picks it up...?
[*/
if (!defined('CIVICRM_UF_BASEURL')) {
  define( 'CIVICRM_UF_BASEURL'      , 'http://www.yorkshirecnd.org.uk/' );
}](url)

**Comment by marsh-circle** [comment]
Hi Deepak,
I have the same issue, it doesn't look like it's prepending the baseURL, and also has lots of URL encoding.
Did you get anywhere with this? are there any settings other than the baseURL in civicrm.settings.php?
the URL in the recieved mail is: 
`"/civicrm/mosaico/img?src=https%3A%2F%2Fwww.xxxxxxxxxxxxxxxxx.org.uk%2Fsites%2Fxxxxxxxxxxxxxxxxx.org.uk%2Ffiles%2Fcivicrm%2Fpersist%2Fcontribute%2Fimages%2Fuploads%2FanImage2_e863ada4fa4774b3fc357c58f2653b1d.png&amp;method=resize&amp;params=350%2Cnull"`

**Comment by mcollopy** [comment]
Hi Deepak, same here on Ubunti 14.04, Drupal 7, 
The test email shows images located at
https://<domain>/civicrm/mosaico/im however where is that location and how is it generated, or found by Drupal or civi?
I didn't see it created so I created it under files, so ic reated it there, under the module and under the drupal codebase but none of it is helping.
I can see images in the gallery now as I upload them, but dragging and dropping intot he template does nothing.
I only recently installed Imagemagick and it seems to be working but is there a temp file location whcih is supposed to be accessed as well?
Even then, where would be the final location of the files?
CiviCRM base is just the domain.

**Comment by deepak-srivastava** [comment]
Might help someone:

Sometimes its some CMS file that adds extra spaces which when combined with rendered image, causes the problem. With one of our wordpress client themes/xxxx/functions.php file had extra spaces in the end.

**Comment by samuelsov** [comment]
I think i have found the problem. The regex rule expect an url starting with an http (in fact starting with h). In my case the url look like "/civicrm/mosaico/img?src=..." so the replacement doesn't work.

So let's change the rule from : 
```
"/src=\"h.+img\?src=(" . $mosaico_image_upload_dir . ")(.+)&.*\"/U" `
```
to 
```
// only removed the "h" so the url can start with any character
"/src=\".+img\?src=(" . $mosaico_image_upload_dir . ")(.+)&.*\"/U"
```

**Comment by kngs** [comment]
I am having this same problem.  In what file would I make this change to see if the above fix solves it for me?

**Comment by MarshCastle** [comment]
Hi kngs,
for me, a recursive grep shows:

```
 ...../sites/[sitedomain]/civicrm_extensions$ rgrep \$mosaico_image_upload_dir uk.co.vedaconsulting.mosaico/ -n
uk.co.vedaconsulting.mosaico/mosaico.php:299:  $mosaico_image_upload_dir = rawurlencode($mosaico_config['BASE_URL'] . $mosaico_config['UPLOADS_URL']);
uk.co.vedaconsulting.mosaico/mosaico.php:302:   "/src=\"h.+img\?src=(" . $mosaico_image_upload_dir . ")(.+)&.*\"/U",
```

so you can either run that command on your machine, or look in that file (the second result -- uk.co.vedaconsulting.mosaico/mosaico.php @around line 302) for the string "$mosaico_image_upload_dir".

Does that help?

**Comment by kngs** [comment]
Yes! I found it and it fixed the image problem for me.
Thank you very much!
