### ISSUE TITLE
http / https mixed content for css and js

### ISSUE THREAD

**Issue by adixon** [veda-consulting-company/uk.co.vedaconsulting.mosaico#76]
I'm getting a green screen when trying to create a new first template, and it's because none of the stylesheets or script files are getting loaded due to the mix content issue.

The site is in https only, and and the getMosaicoDistUrl looks like it should be okay with that, but there's some fancy new Tim code in there that exceeds my lazy debugging efforts today.

Clues? The base url in the civi settings had been set to http, and I changed that, so perhaps those values are just really stuck in some cache somewhere? I tried the usual, including uninstalling and reinstalling the extension.

It's civi 4.6.24 and drupal 7.

**Comment by axon-obriend** [comment]
I'm not sure if it's the same problem, but check out issue #87. You might be having the same outdated metadata problem I was.

**Comment by adixon** [comment]
Great clue, thanks.
